name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # executa todo dia à meia-noite
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: laricel
          outputs: |
            ./github-contribution-grid-snake.svg

      - name: Commit and push
        uses: EndBug/add-and-commit@v9
        with:
          message: "Generate GitHub contribution snake"
          add: "*.svg"
